config/routes.rb
Rails.application.routes.draw do

  root 'messages#index' 
  
  get 'password_resets/new'
  get 'password_resets/edit'

  get    'login'   => 'logins#new'
  post   'login'   => 'logins#create'
  delete 'logout'  => 'logins#destroy'
  
  get 'signup'  => 'authors#new'

  resources :authors do 
    member do 
      post 'follow'
      post 'unfollow'
      get 'inbox/:message' => 'authors#inbox', as: :inbox
    end
    
  end
  
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
      get :send, to: 'conversations#new', as: :send
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get '/posts_with_button', to: 'messages#index_with_button', as: 'posts_with_button'
  get 'favourites/:author' => 'messages#streams', as: 'list_favourites'
  resources :messages do 
    collection do 
      get 'streams/:stream', :action => :streams, :as => "streams"
    end
    member do 
      post 'favourite'
      post 'unfavourite'
    end
  end

  resources :users
  get 'home/:username' => 'static_pages#home', as: :username
  get 'home' => 'static_pages#home'
 
  
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_fail'
  get '/sign_out', to: 'sessions#destroy', as: :sign_out
  
  resources :comments, only: [:new, :create, :show, :destroy] do 
    member do 
      post 'vote'
    end
  end
 end

app/models/message.rb
class Message < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
	validate  :picture_size
	
	has_and_belongs_to_many :favourites, :join_table => "favourites", :class_name => "Author", :association_foreign_key => "fav_author_id"
	belongs_to :author
	validates :contents, :length => { :minimum => 3, :maximum => 140 }

	scope :followed_by, -> id {where("author_id IN (SELECT follow_id FROM author_follows WHERE author_id = ?)", id)}
    default_scope { order('created_at DESC') }
	
	def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
	end
	
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json
  
    def index
      @title = "Latest messages"
      @the_message = Message.new
      get_and_show_posts
    end

    def index_with_button
      get_and_show_posts
    end

  def streams
    if params[:stream] == 'favourites' || params[:author]
      @title = "Favourite messages"
      params[:author] ? author = Author.find(params[:author]) : author = @author
      @messages = author.favourites.all.paginate(:page => params[:page], :per_page => 3)
    elsif params[:stream] == 'followed'
      @title = "Followed messages"
      @messages = @author.followed_messages.all.paginate(:page => params[:page], :per_page => 3)
    end
    render :action => :index
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = Message.new
  end

  def edit
  end

  def favourite
    message = Message.find(params[:id])
    @author.favourites << message unless @author.favourites.include? message
    redirect_to messages_url
  end
  
  def unfavourite 
    message = Message.find(params[:id])
    @author.favourites.delete(message) if @author.favourites.include? message
  end

  def create
    @the_message = Message.new(message_params)
    @the_message.author = @author
    respond_to do |format|
      if @the_message.save
        format.html { redirect_to messages_path }
        format.js { }
        
      else
        format.html { render :new }
        format.json { render json: @the_message.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  before_filter :login
  private
  
    def get_and_show_posts
      @messages = Message.paginate(page: params[:page], per_page: 8).order('created_at DESC')
      respond_to do |format|
        format.html
        format.js
      end
    end
  
    def set_message
      @message = Message.find(params[:id])
    end

     def message_params
       params.require(:message).permit(:contents, :stream, :picture, :author)
     end

    def login
      author_id = session[:author_id]
      if author_id != nil 
        @author = Author.find(author_id)
      else 
        redirect_to login_url, :alert => "You must login"
      end
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def gravatar_for(author, options={size:80})
    gravatar_id = Digest::MD5::hexdigest(author.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: author.full_name, class: "gravatar")
  end
end

app/views/messages/_form.html.erb
<% if @the_message.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@the_message.errors.count, "error") %> prohibited this message from being saved:</h2>
		<ul>
			<% @the_message.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<% doajax = false unless (defined? doajax) %>
<%= form_for(@the_message, remote: doajax, html: { multipart: true }) do |f| %>

  	<div class="col-md-4">
  		<div class="form-group">
				<span class="picture">
					<%= f.label :picture %>
    			<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    			<%= f.submit %>
  			</span>
			</div>
  	</div>
  	<div class="col-md-4">
  		<div class="form-group">
				<%= f.label :contents %><br />
				<%= f.text_area :contents %>
			</div>
  	</div>

<% end %>

<script type="text/javascript">
  $('#the_message_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/messages/_list.html.erb
<%= will_paginate messages %>
<% messages.in_groups_of(4, false).each do |group| %>
  <div class='row'>
    <% group.each do |message| %>
    
      <div class='col-md-3'>
        <%= image_tag(message.picture.url, class: "img-responsive") %>
	        <div class="caption">
	        	<% if message.author != nil %>
							<%= gravatar_for message.author, size: 50, :class => "img-gravatar" %>
							<%= link_to message.author.username, message, :class => "img-name" %>
					
				 	  <% end %>
	       </div>
      </div>
      
    <% end %>
  </div>
<% end %>

	

app/views/messages/_message.html.erb
<div class='col-md-3'>

	<div class="add_favourite">
		<div class='col-md-4'>
			<% if !current_author?(message.author) && !current_author.favourites.include?(message) %>
				<%= link_to "Add?", favourite_message_path(id: message), method: :post %>
			<% end %>
			<% if current_author.favourites.include? message %>
				<%= link_to "Unadd?", unfavourite_message_path(id: message), method: :post %>
			<% end %>
		</div>
		<div class='col-md-8'>
			Favs: <%= message.favourites.count %>
		</div>
	</div>	
	<%= image_tag(message.picture.url, class: "img-responsive") %>
	<div class="caption">
	  <% if message.author != nil %>
	    <%= link_to message.author.username, message, :class => "img-name" %>
			<div class="gravatar">
				
				<%= gravatar_for message.author, size: 50, :class => "img-gravatar" %>
				<div class="effect">
					<%= truncate(message.contents, length: 20) %> <br/>
						<div style="display:inline;"class="follow">
							<% if message.author != nil and message.author != @author and not @author.follows.include?(message.author) %>
								<%= form_tag(follow_author_path(message.author)) do %>
									<%= submit_tag "Follow #{message.author.username}?", :class=>"btn btn-link" %>  
								<% end %>
							<% elsif @author.follows.include?(message.author) %>
								<%= form_tag(unfollow_author_path(message.author)) do %>
									<%= submit_tag "Unfollow #{message.author.username}?", :class=>"btn btn-link" %>
								<% end %>
							<% end %>
			      </div>	
				</div>
			</div>
		<% end %>
	</div>

</div>

app/views/messages/create.js.erb
<table>
	<tr>
		<td>
			<div style="height: 73px; width: 73px; overflow: hidden">
				<% if @the_message.author != nil %>
					<img src="<%= @the_message.author.image %>" width="73"/>
				<% end %>
			</div>
		</td>
		<td>
			<%= @the_message.contents %>
			<br/>
			<div class="favorites">
				Favorites: <%= @the_message.favourites.size %>
				<%= form_tag(favourite_message_path(@the_message)) do %>
					<%= submit_tag "Add as favorite" %>
				<% end %>
			</div>
			<div class="follow">
				<% if @the_message.author != nil and @the_message.author != @author and not @author.follows.include?(@the_message.author) %>
					<%= form_tag(follow_author_path(@the_message.author)) do %>
						<%= submit_tag "Follow author" %>
					<% end %>
				<% end %>
			</div>
		</td>
	</tr>
</table>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<% provide(:title, "Latest Photos") %>
<div class="page-header">
  <h1>Latest Photos</h1>
</div>

<div id="static-pagination">
  <%= will_paginate %>
</div>

<div id="my-posts">
  <div class="page-delimiter first-page" data-page="<%= params[:page] || 1 %>"></div>
  <% @messages.in_groups_of(4, false).each do |group| %>
    <div class='row'>
      <% group.each do |message| %>
       <%= render partial: "message", locals: { message: message } %>
      <% end %>
    </div>
  <% end %>
</div>
    
<% if @messages.next_page %>
  <div id="infinite-scrolling">
    <%= will_paginate %>
  </div>
<% end %>

app/views/messages/index.js.erb
var delimiter =
        $('<div class="page-delimiter" data-page="<%= params[:page] %>"></div>');
$('#my-posts').append(delimiter);
$('#my-posts').append('<%= j render @messages %>');
$('.pagination').replaceWith('<%= j will_paginate @messages %>');
preparePagination(delimiter);
<% unless @messages.next_page %>
$('#infinite-scrolling .pagination').remove();
<% end %>

app/views/messages/index_with_button.html.erb
<div class="page-header">
  <h1>My posts</h1>
</div>

<div id="static-pagination">
  <%= will_paginate %>
</div>

<div id="my-posts">
  <div class="page-delimiter first-page" data-page="<%= params[:page] || 1 %>"></div>
  <%= render @messages %>
</div>

<% if @messages.next_page %>
    <div id="with-button">
      <%= will_paginate %>
    </div>

    <div id="load_more_posts" class="btn btn-primary btn-lg">More posts</div>
<% end %>

app/views/messages/index_with_button.js.erb
var delimiter =
        $('<div class="page-delimiter" data-page="<%= params[:page] %>"></div>');
$('#my-posts').append(delimiter);
$('#my-posts').append('<%= j render @messages %>');
$('.pagination').replaceWith('<%= j will_paginate @messages %>');
preparePagination(delimiter);
<% if @messages.next_page %>
$('#with-button .pagination').hide();
<% else %>
$('#with-button .pagination, #load_more_posts').remove();
<% end %>

app/views/messages/new.html.erb
<% provide(:title, "New Message") %>
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<% provide(:title, @message.author.username + 's Message') %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Contents:</strong>
  <%= @message.contents %>
</p>
<p>
	<%= @message.author.email %>
</p>

<%= link_to 'Back', messages_path %>