config/routes.rb
Rails.application.routes.draw do

  root 'messages#index' 
  
  get 'password_resets/new'
  get 'password_resets/edit'

  get    'login'   => 'logins#new'
  post   'login'   => 'logins#create'
  delete 'logout'  => 'logins#destroy'
  
  get 'signup'  => 'authors#new'

  resources :authors do 
    member do 
      post 'follow'
      post 'unfollow'
      get 'inbox/:message' => 'authors#inbox', as: :inbox
    end
    
  end
  
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
      get :send, to: 'conversations#new', as: :send
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get '/posts_with_button', to: 'messages#index_with_button', as: 'posts_with_button'
  get 'favourites/:author' => 'messages#streams', as: 'list_favourites'
  resources :messages do 
    collection do 
      get 'streams/:stream', :action => :streams, :as => "streams"
    end
    member do 
      post 'favourite'
      post 'unfavourite'
    end
  end

  resources :users
  get 'home/:username' => 'static_pages#home', as: :username
  get 'home' => 'static_pages#home'
 
  
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_fail'
  get '/sign_out', to: 'sessions#destroy', as: :sign_out
  
  resources :comments, only: [:new, :create, :show, :destroy] do 
    member do 
      post 'vote'
    end
  end
 end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

	def new
	end

  def form 
  end

	def create 
		author = Author.find_by(username: params[:login][:username].downcase)
		if author && author.authenticate(params[:login][:password])
			if author.activated?
    		log_in author
    		params[:login][:remember_me] == '1' ? remember(author) : forget(author)
    		# send_back_or author
    		redirect_to author
    	else
    		message = "Account not activated"
    		message += "Check your email for the activation link."
        redirect_to login_url
			end
		else
    	flash.now[:danger] = "wrong credentials"
			render 'new'
		end
	end
	
	def destroy 
		log_out if logged_in?
    redirect_to root_url
	end

end

app/helpers/logins_helper.rb
module LoginsHelper
  
  def log_in(author)
    session[:author_id] = author.id
  end
  
  def remember(author)
    author.remember
    cookies.permanent.signed[:author_id] = author.id
    cookies.permanent[:remember_token] = author.remember_token
  end
   
  def current_author?(author)
    author == current_author
  end
  
  def current_author
    if (author_id = session[:author_id])
      @current_author ||= Author.find_by(id: author_id)
    elsif (author_id = cookies.signed[:author_id])
      author = Author.find_by(id: author_id)
      if author && author.authenticated?(:remember, cookies[:remember_token])
        log_in author
        @current_author = author
      end
    end
  end
  
  def logged_in?
    !current_author.nil?
  end
  
  def forget(author)
    author.forget
    cookies.delete(:author_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current author.
  def log_out
    forget(current_author)
    cookies.delete(:user_id)
    session.delete(:author_id)
    @current_author = nil
  end
  
  def send_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def save_url
    session[:forwarding_url] = request.url if request.get?
  end
  
end

app/views/logins/form.html.erb
<% provide(:title, "Login") %>
<% if flash[:alert] %>
	<p id="notice"><%= flash[:alert] %></p>
<% end %>
<%= form_tag do %>
	<fieldset>
	<legend>Login:</legend>
	<div>
		<%= label_tag :name, 'Username:' %>
		<%= text_field_tag :username, params[:username] %>
	</div>
	<div>
		<%= label_tag :password, 'Password:' %>
		<%= password_field_tag :password, params[:password] %>
	</div>
	<div>
		<%= submit_tag "Login" %>
	</div>
	</fieldset>
<% end %>

app/views/logins/login.html.erb
<h1>Logins#login</h1>
<p>Find me in app/views/logins/login.html.erb</p>

app/views/logins/logout.html.erb
<h1>Logins#logout</h1>
<p>Find me in app/views/logins/logout.html.erb</p>

app/views/logins/new.html.erb
<% provide(:title, "Login") %>
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:login, url: login_path) do |f| %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :remember_me, class: "checkbox inline" do %>
        <%= f.check_box :remember_me %>
        <span>Remember me</span>
      <% end %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

    <p>
      <span>New user? <%= link_to "Sign up now!", signup_path %></span>
     <span style="float:right;"><%= link_to "Forgot password?", new_password_reset_path %></span>
    </p>
  </div>
</div>