config/routes.rb
Rails.application.routes.draw do

  root 'messages#index' 
  
  get 'password_resets/new'
  get 'password_resets/edit'

  get    'login'   => 'logins#new'
  post   'login'   => 'logins#create'
  delete 'logout'  => 'logins#destroy'
  
  get 'signup'  => 'authors#new'

  resources :authors do 
    member do 
      post 'follow'
      post 'unfollow'
      get 'inbox/:message' => 'authors#inbox', as: :inbox
    end
    
  end
  
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
      get :send, to: 'conversations#new', as: :send
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get '/posts_with_button', to: 'messages#index_with_button', as: 'posts_with_button'
  get 'favourites/:author' => 'messages#streams', as: 'list_favourites'
  resources :messages do 
    collection do 
      get 'streams/:stream', :action => :streams, :as => "streams"
    end
    member do 
      post 'favourite'
      post 'unfavourite'
    end
  end

  resources :users
  get 'home/:username' => 'static_pages#home', as: :username
  get 'home' => 'static_pages#home'
 
  
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_fail'
  get '/sign_out', to: 'sessions#destroy', as: :sign_out
  
  resources :comments, only: [:new, :create, :show, :destroy] do 
    member do 
      post 'vote'
    end
  end
 end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest

  validates :username, uniqueness: true, presence: true, length: { maximum: 30 }
  validates :password, presence: true, length: { minimum: 6, maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  
  acts_as_messageable
   
  has_and_belongs_to_many :favourites, :join_table => "favourites", :class_name => "Message", :foreign_key => "fav_author_id"
  has_and_belongs_to_many :authors_users, :join_table => "authors_users", :class_name => "User", :association_foreign_key => "join_user_id"
  has_many :author_follows
  has_many :follows, :through => :author_follows
  has_many :follow_authors, :class_name => "AuthorFollow", :foreign_key => :follow_id 
  has_many :followers, :through => :follow_authors, :source => :author 


  def name
    return downcase_email
  end
  
  def mailboxer_email(object)
    return downcase_email
  end
  
  def followed_messages 
    Message.followed_by(self.id)
  end
  
  def Author.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
    
  def Author.new_token
    SecureRandom.urlsafe_base64
  end
    
  def remember
    self.remember_token = Author.new_token
    update_attribute(:remember_digest, Author.digest(remember_token))
  end
  
 # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    AuthorMailer.account_activation(self).deliver
  end
  
  def create_reset_digest
    self.reset_token = Author.new_token
    update_attribute(:reset_digest,  Author.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    AuthorMailer.password_reset(self).deliver
  end
  
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  private 
  
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = Author.new_token
      self.activation_digest = Author.digest(activation_token)
    end
  
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :logged_in_author, only: [:index, :edit, :update, :destroy]
  before_action :correct_author,   only: [:edit, :update]
  before_action :admin_author,     only: :destroy
  
  def index
    @authors = Author.paginate(page: params[:page])
  end

  def show
    @author = Author.find(params[:id])
    if current_author?(@author)
      @inbox = current_author.mailbox.inbox.paginate(page: params[:inbox_page], per_page: 2)
      @conversations = current_author.mailbox.conversations.paginate(page: params[:conversations_page], per_page: 2)
      @sent = current_author.mailbox.sentbox.paginate(page: params[:sent_page], per_page: 2)
    else
      redirect_to author_url(current_author)
    end
  end
  
  def inbox
    author = Author.find(params[:id])
    @conversation = author.mailbox.inbox.find(params[:message])
    @receipts = @conversation.receipts_for author
    
   respond_to do |format|
      format.html
      format.pdf do
        pdf = InboxPdf.new(@receipts,@conversation)
        send_data pdf.render, filename: 'inbox.pdf', type: 'application/pdf'
      end
    end
 
  end

  def new
    @author = Author.new
  end

  def edit
    @author = Author.find(params[:id])
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      @author.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to login_url
     else
      render 'new'
    end
  end
  

  def update
    @author = Author.find(params[:id])
    if @author.update_attributes(author_params)
      flash[:success] = "Profile updated"
      redirect_to @author
    else
      render 'edit'
    end
  end

  def destroy
    Author.find(params[:id]).destroy
    flash[:success] = "Author deleted"
    redirect_to authors_url
  end

  def follow 
    author_id = session[:author_id]
    if author_id != nil 
      logged_in_author = Author.find(author_id)
      author = Author.find(params[:id])
      author.followers << logged_in_author unless author.followers.include? logged_in_author 
      redirect_to messages_url 
    else 
      redirect_to login_url, :alert => "You must login"
    end
  end
  
  def unfollow 
    author_id = session[:author_id]
    if author_id != nil 
      logged_in_author = Author.find(author_id)
      author = Author.find(params[:id])
      logged_in_author.follows.delete(author) if author.followers.include? logged_in_author 
      redirect_to messages_url
    else
      redirect_to login_url, :alert => "You must login"
    end
  end

  private

    def author_params
      params.require(:author).permit(:username, :password, :password_confirmation, :email, :message)
    end
    
    def correct_author
      @author = Author.find(params[:id])
      redirect_to(root_url) unless current_author?(@author)
    end
    
    def admin_author
      redirect_to(root_url) unless current_author.admin?
    end
    
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.erb
<li>
  <%= gravatar_for author, size: 50 %>
  <%= link_to author.username, username_path(author.username) %>
   <% if current_author.admin? && !current_author?(author) %>
    | <%= link_to "delete", author, method: :delete,
                                  data: { confirm: "You sure?" } %>
    <% end %>
</li>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@author.errors.count, "error") %>.
      </div>
      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="row">
     <div class="col-md-6 col-md-offset-3">

       <%= f.label :username %><br>
       <%= f.text_field :username, class: 'form-control' %>
    
       <%= f.label :email %><br>
       <%= f.text_field :email, class: 'form-control' %>
      
      <%= f.label :password %><br>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create Author", class: "btn btn-primary" %>
   
    
  </div>
</div>

<% end %>

app/views/authors/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Editing author</h1>

<div class="row">
<%= link_to 'Mail', @author %> |
<%= link_to 'Back', authors_path %>
</div>

<div class="row">
  <div class="col-md-3">
    <div class="gravatar_edit">
      <%= gravatar_for @author %>
      <a href="http://gravatar.com/emails" target=_blank>Change your Gravatar</a>
    </div>
  </div>
  <div class="col-md-6">
    <%= form_for(@author) do |f| %>
      <%= render 'shared/error_messages' %>

       <%= f.label :full_name %><br>
       <%= f.text_field :full_name, class: 'form-control' %>
       
       <%= f.label :username %><br>
       <%= f.text_field :username, class: 'form-control' %>
    
       <%= f.label :email %><br>
       <%= f.text_field :email, class: 'form-control' %>
      
      <%= f.label :password %><br>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
  
      <%= f.label :profile %><br>
      <%= f.text_area :profile, class: 'form-control' %>

      <%= f.submit "Edit Author", class: "btn btn-primary" %>
    <% end %>
  </div>

</div>

app/views/authors/inbox.html.erb
Messages From: <%= @conversation.originator.username %> | <%= @conversation.originator.email %> <br/>
Sent On: <%= @conversation.created_at.to_formatted_s(:long) %> <br/>

<% @receipts.each do |receipt| %> 
  Status: <%= receipt.is_unread? ? "read" : "unread" %><br/>
  <% author = Author.find(receipt.receiver_id) %>
  <% message = receipt.message %>
  Subject: <%= message.subject %> Sent to: <%= author.email %><br/>
  Contents:<br/>
  <%= message.body %>
<% end %>

app/views/authors/index.html.erb
<% provide(:title, 'All Authors') %>
<h1>All Authors</h1>
<%= will_paginate %>
  <ul class="authors">
    <%= render @authors %>
  </ul>
<%= will_paginate %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>
<div class='row'>
  <div class="col-md-6">
    <h1 style="text-align:left;"><%= gravatar_for @author, size: 50 %>
    <%= @author.username %></h1>
  </div>

  <div class="col-md-6">
    <ul class="author-activity">
      <li>Followers: <%= @author.followers.count %></li>
      <li>Following: <%= @author.follows.count%> </li>
      <li><%= link_to "Favourties: #{@author.favourites.count}", list_favourites_path(:author => @author) %></li>
    </ul>
  </div>
</div>
<div class='row'>
  <div class="col-md-4">
    <h2>Inbox</h2>
    <% @inbox.each do |message| %>
      <p>
        <%= link_to(message.subject, inbox_author_path(:id => @author, :message => message.id)) %> | 
        From <%= link_to(message.originator.username, username_path(:username => message.originator.username)) %> | 
        sent at: <%= message.created_at %>
      </p>
      <p><%= link_to "Download PDF", inbox_author_path(:id => @author, :message => message.id, :format => 'pdf') %></p>
    <% end %>
    <%= will_paginate @inbox, :param_name => 'inbox_page' %>
    <%= link_to "New Message", new_conversation_path, class: "btn btn-primary mail" %>
  </div>

  <div class="col-md-4">
    <h2>Conversations</h2>
    <% @conversations.each do |conversation| %>
      <p>
        <% if conversation.originator.username != current_author.username %>
          <%= link_to("conversation", inbox_author_path(:id => current_author, :message => conversation.id)) %> |
          From: <%= conversation.originator.username %> | Sent at: <%= conversation.created_at %>
        <% else %>
          <% conversation.recipients.each do |recipient| %>
            <% if recipient.id != current_author.id %>
              <%= link_to("conversation", inbox_author_path(:id => recipient.id, :message => conversation.id)) %> |
              From: <%= conversation.originator.username %> | Sent at: <%= conversation.created_at %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    <%= will_paginate @conversations, :param_name => 'conversations_page' %>
  </div>
  
  <div class="col-md-4">
    <h2>Sent Messages</h2>
    <% @sent.each do |message| %>
      <% message.recipients.each do |recipient| %>
        <% if recipient.id != current_author.id %>
          <p><%= link_to(message.subject, inbox_author_path(:id => recipient.id, :message => message.id)) %> |
           Sent at: <%= message.created_at %></p>
        <% end %>
      <% end %>
    <% end %>
    <%= will_paginate @sent, :param_name => 'sent_page' %>
  </div>
  

  
</div>