config/routes.rb
Rails.application.routes.draw do

  root 'messages#index' 
  
  get 'password_resets/new'
  get 'password_resets/edit'

  get    'login'   => 'logins#new'
  post   'login'   => 'logins#create'
  delete 'logout'  => 'logins#destroy'
  
  get 'signup'  => 'authors#new'

  resources :authors do 
    member do 
      post 'follow'
      post 'unfollow'
      get 'inbox/:message' => 'authors#inbox', as: :inbox
    end
    
  end
  
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
      get :send, to: 'conversations#new', as: :send
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get '/posts_with_button', to: 'messages#index_with_button', as: 'posts_with_button'
  get 'favourites/:author' => 'messages#streams', as: 'list_favourites'
  resources :messages do 
    collection do 
      get 'streams/:stream', :action => :streams, :as => "streams"
    end
    member do 
      post 'favourite'
      post 'unfavourite'
    end
  end

  resources :users
  get 'home/:username' => 'static_pages#home', as: :username
  get 'home' => 'static_pages#home'
 
  
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_fail'
  get '/sign_out', to: 'sessions#destroy', as: :sign_out
  
  resources :comments, only: [:new, :create, :show, :destroy] do 
    member do 
      post 'vote'
    end
  end
 end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <p class="text-muted"></p>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
       <%= link_to "Photo Scroll", home_path, id: "logo", class: "thelogo", style: "margin-top: .55%;" %>
      <ul class="nav navbar-nav pull-right">
        <% if current_user %>
          <li><%= image_tag current_user.avatar_url, style:"height:4.15em;" %></li>
          <li><%= link_to 'Home', home_path %></li>
        <% end %>
        <% if logged_in? %>

          <li><%= link_to 'Mail', author_path(current_author) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Site <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Chat', new_comment_path %></li>
              <li><%= link_to "Photos", messages_path %></li>
              <li><%= link_to "Authors", authors_path %></li>
              <li><%= link_to "Settings", edit_author_path(current_author) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
       <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
   	<%= render 'layouts/footer' %>
   	<%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/layouts/images.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<div style="float:right">
			Signed in as: <strong><%= @author.full_name %></strong>
		</div>

		<%= form_tag(images_find_path, :method => "get", id: "search-form") do %>
			<%= text_field_tag :search, params[:search], placeholder: "Search" %>
			<%= submit_tag "Search", :name => nil %>
		<% end %>

		<div style="display:table-cell; width: 200px;">
			<h1>Photos</h1>
			<ul>
				<li><%= link_to_unless_current 'All photos', :images %></li>
				<li><%= link_to_unless_current 'Fivestar photos', :images_fivestar %></li>
				<li><%= link_to_unless_current 'New photo', :new_image %></li>
			</ul>
		</div>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/layouts/messages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">

	<div class='row'>
		<% if @the_message then %>
			<%= render 'form' %>
		<% end %>
		<div class="col-md-4">
			<div class='row'>
				<div class="col-md-4 text-center"><strong>Messages</strong></div>
			</div>
			<div class='row'>
				<div class="col-md-1"><%= link_to_unless_current "All", :controller => "messages", :action => "index" %></div>
				<div class="col-md-2"><%= link_to_unless_current "Followed", :controller => "messages", :action => "streams", :stream => "followed" %></div>
				<div class="col-md-1">
					<% unless params[:author] %>
						<%= link_to_unless_current "Favourites", :controller => "messages", :action => "streams", :stream => "favourites" %>
					<% end %>
				</div>
			</div>
  	</div>
	</div>
	<%= yield %>
	<%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/layouts/tasks.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div style="float: right">
		Signed in as: <strong><%= @author.full_name %></strong>
	</div>

	<%= form_tag(tasks_search_path, :method => "get", id: "search-form") do %>
  		<%= text_field_tag :search, params[:search], placeholder: "Search" %>
   		<%= submit_tag "Search", :name => nil %>
  	<% end %>
  
	<div style="display:table-cell; width: 200px;">
		<h1>TASKS</h1>
		<ul>
			<li><%= link_to_unless_current 'All tasks', :tasks %></li>
			<li><%= link_to_unless_current 'Incomplete tasks', :tasks_incomplete %></li>
			<li><%= link_to_unless_current 'New task', :new_task %></li>
		</ul>
	</div>
	<%= yield %>
	<hr>
	<h4>Copyright</h4>
	<p> &#169; Copyright 2014 PhotoScroll Unltd.</p>
	<hr>
</body>
</html>